/* ---------------------------------------------------- */
/* Generated by Enterprise Architect Version 13.0
*/
/* DBMS
: PostgreSQL
*/
/* ---------------------------------------------------- */
CREATE TABLE funcao_usuario_externo
(
	co_funcao serial NOT NULL, -- Código único da funcao do usuário externo
	no_funcao varchar(50) NOT NULL -- nome da funcao do usuário externo
);

ALTER TABLE funcao_usuario_externo ADD CONSTRAINT pk_eprtb016
PRIMARY KEY (co_funcao);

CREATE TABLE usuario_externo
(
	nu_cpf varchar(11) NOT NULL, -- Número do cpf do usuário
	no_usuario varchar(60) NOT NULL, -- Nome do Usuário
	de_email varchar(255) NOT NULL, -- email do usuário
	ic_situacao varchar(1) NOT NULL, -- Situação, onde: A-Ativo, I-Inativo
	ic_perfil_acesso smallint NOT NULL, -- Perfil do usuário: 0-Aluno, 1-Gestor Municipal, 2-Gestor Estadual, 3-Gestor Nacional
	co_funcao smallint NOT NULL,-- Código único da funcao do usuário externo
	nu_telefone varchar(11)-- número do telefone
);
/* Create Primary Keys, Indexes, Uniques, Checks */
ALTER TABLE usuario_externo ADD CONSTRAINT pk_eprtb008
PRIMARY KEY (nu_cpf);

/* Create Foreign Key Constraints */
ALTER TABLE usuario_externo ADD CONSTRAINT FK_eprtb008_eprtb016
FOREIGN KEY (co_funcao) REFERENCES funcao_usuario_externo (co_funcao) ON DELETE
No Action ON UPDATE No Action;

INSERT INTO funcao_usuario_externo(co_funcao, no_funcao) VALUES (1, 'Gestor');
INSERT INTO funcao_usuario_externo(co_funcao, no_funcao) VALUES (2, 'Administrador');
INSERT INTO funcao_usuario_externo(co_funcao, no_funcao) VALUES (3, 'Frente de Caixa');